import { StyleSheet } from "react-native";

export const stylesLight = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  topContainer: {
    height: "15%",
    paddingTop: 50,
    width: "100%",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "gray",
    width: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  contentContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 20,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  descriptionContainer: {
    backgroundColor: "lightgray",
    padding: 10,
    borderRadius: 10,
    marginLeft: 10,
    width: "70%",
  },
  descriptionTitle: {
    textAlign: "center",
    fontWeight: "700",
    fontSize: 20,
  },
  descriptionText: {
    textAlign: "center",
  },
  sectionTitle: {
    color: "black",
    fontWeight: "900",
    textTransform: "capitalize",
    fontSize: 20,
    textAlign: "center",
  },
  scrollContainer: {
    paddingHorizontal: 10,
    marginVertical: 10,
    width: "100%",
  },
  favoritesItem: {
    borderColor: "black",
    borderWidth: 1,
    borderStyle: "dashed",
    padding: 10,
    marginVertical: 5,
    color: "darkred",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "italic",
    fontSize: 16,
    backgroundColor: "silver",
  },
  qrContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  contactContainer: {
    alignItems: "center",
    marginTop: 20,
    padding: 10,
  },
  contactImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 10,
  },
  contactText: {
    fontSize: 16,
    textAlign: "center",
    color: "black",
  },
});

export const stylesDark = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
    alignItems: "center",
  },
  topContainer: {
    height: "15%",
    paddingTop: 50,
    width: "100%",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "#1F1F1F",
    width: "100%",
    color: "#FFFFFF",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  contentContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 20,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  descriptionContainer: {
    backgroundColor: "#333333",
    padding: 10,
    borderRadius: 10,
    marginLeft: 10,
    width: "70%",
  },
  descriptionTitle: {
    textAlign: "center",
    fontWeight: "700",
    fontSize: 20,
    color: "#FFFFFF",
  },
  descriptionText: {
    textAlign: "center",
    color: "#BBBBBB",
  },
  sectionTitle: {
    color: "#BB86FC",
    fontWeight: "900",
    textTransform: "capitalize",
    fontSize: 20,
    textAlign: "center",
  },
  scrollContainer: {
    paddingHorizontal: 10,
    marginVertical: 10,
    width: "100%",
  },
  favoritesItem: {
    borderColor: "white",
    borderWidth: 1,
    borderStyle: "dashed",
    padding: 10,
    marginVertical: 5,
    color: "lightgray",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "italic",
    fontSize: 16,
    backgroundColor: "#444444",
  },
  qrContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  contactContainer: {
    alignItems: "center",
    marginTop: 20,
    padding: 10,
  },
  contactImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 10,
  },
  contactText: {
    fontSize: 16,
    textAlign: "center",
    color: "white",
  },
});
